version: '3'
services:
  bigdata-app:
    image: rehanalimahomed/bigdata-market-insight:latest
    ports:
      - "8080:8080" # Port de l'hôte:Port du conteneur
    environment:
      - DB_HOST=mongodb
      - DB_NAME=BigData
      - DB_USERNAME=
      - DB_PASSWORD=
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=BigData

